rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'androidingest'
    static_configs:
      - targets: ['skia-android-ingest:20000']

  - job_name: 'collectd'
    static_configs:
      - targets: ['skia-monitoring:20002']

  - job_name: 'corpproxy'
    static_configs:
      - targets: ['skia-proxy:20000']

  - job_name: 'ct-poller'
    static_configs:
      - targets: ['skia-ct-master:20000']

  - job_name: 'ctfe'
    static_configs:
      - targets: ['skia-ctfe:20000']

  - job_name: 'debugger'
    static_configs:
      - targets: ['skia-debugger:20000']

  - job_name: 'datahopper'
    static_configs:
      - targets: ['skia-datahopper2:20000']

  - job_name: 'docserver'
    static_configs:
      - targets: ['skia-docs:20000']

  - job_name: 'fiddle'
    static_configs:
      - targets: ['skia-fiddle:20000']

  - job_name: 'imageinfo'
    static_configs:
      - targets: ['skia-imageinfo:20000']

  - job_name: 'proberd'
    static_configs:
      - targets: ['skia-monitoring:20000']

  - job_name: 'logmetrics'
    static_configs:
      - targets: ['skia-monitoring:20001']

  - job_name: 'push'
    static_configs:
      - targets: ['skia-push:20000']

  - job_name: 'skiaperfd'
    static_configs:
      - targets: ['skia-perf:20000']
      - targets: ['skia-android-perf:20000']

  - job_name: 'pulld'
    static_configs:
      - targets: ['catapult-autoroll:11000']
      - targets: ['nacl-autoroll:11000']
      - targets: ['pdfium-autoroll:11000']
      - targets: ['skia-alerts:11000']
      - targets: ['skia-android-ingest:11000']
      - targets: ['skia-android-perf:11000']
      - targets: ['skia-autoroll:11000']
      - targets: ['skia-cq-watcher:11000']
      - targets: ['skia-datahopper2:11000']
      - targets: ['skia-debugger:11000']
      - targets: ['skia-docs:11000']
      - targets: ['skia-fiddle:11000']
      - targets: ['skia-fuzzer-be-1:11000']
      - targets: ['skia-fuzzer-be-2:11000']
      - targets: ['skia-fuzzer-fe:11000']
      - targets: ['skia-gold-pdfium:11000']
      - targets: ['skia-gold-prod:11000']
      - targets: ['skia-gold-stage:11000']
      - targets: ['skia-imageinfo:11000']
      - targets: ['skia-internal:11000']
      - targets: ['skia-monitoring:11000']
      - targets: ['skia-monitoring:11000']
      - targets: ['skia-perf:11000']
      - targets: ['skia-prom:11000']
      - targets: ['skia-proxy:11000']
      - targets: ['skia-push:11000']
      - targets: ['skia-skfe-1:11000']
      - targets: ['skia-skfe-2:11000']
      - targets: ['skia-status:11000']
      - targets: ['skia-task-scheduler-internal:11000']
      - targets: ['skia-task-scheduler:11000']
      - targets: ['skia-tracedb:11000']

  # Prometheus self monitoring.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['skia-prom:8000']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['skia-prom:8001']

  - job_name: 'prom-proxy'
    static_configs:
      - targets: ['skia-prom:20002']

  - job_name: 'alert-proxy'
    static_configs:
      - targets: ['skia-prom:20003']

  - job_name: 'webhook-proxy'
    static_configs:
      - targets: ['skia-prom:20004']

