GitRepoDir     = "./skia"              # Directory location for the Skia repo.

[Ingesters]
	### Gold ingester ############################################################
	[Ingesters.gold]
	RunEvery       = "15m"                        # How often the ingester should pull data from Google Storage.
	NCommits       = 100                          # Minimum number of commits that should be ingested.
	MinDays        = 21                           # Minimum number of days that should be covered by the ingested commits.
	StatusDir      = "./ingest_status"            # Path where the ingest process keeps its status between restarts.
	MetricName     = "gold-ingest"         # Graphite metric name to use for this ingester

		[[Ingesters.gold.Sources]]
		Bucket         = "chromium-skia-gm"
		Dir            = "dm-json-v1"

		[[Ingesters.gold.Sources]]
		Bucket         = "skia-infra-gm"
		Dir            = "dm-json-v1"

		[Ingesters.gold.ExtraParams]
		TraceService   = "localhost:9091"


	### Gold trybot ingester #####################################################
	[Ingesters.gold-trybot]
	RunEvery       = "15m"                        # How often the ingester should pull data from Google Storage.
	NCommits       = 100                          # Minimum number of commits that should be ingested.
	MinDays        = 21                           # Minimum number of days that should be covered by the ingested commits.
	StatusDir      = "./ingest_status"            # Path where the ingest process keeps its status between restarts.
	MetricName     = "gold-ingest-trybot"         # Graphite metric name to use for this ingester

		[[Ingesters.gold-trybot.Sources]]
		Dir            = "dm-json-v1"

		[Ingesters.gold-trybot.ExtraParams]
		TraceService   = "localhost:9091"


	### Nano bench ingester ############################################################
	[Ingesters.nano]
	RunEvery       = "15m"
	NCommits       = 100
	MinDays        = 21
	StatusDir      = "./ingest_status"
	MetricName     = "nano-ingest"

		[[Ingesters.nano.Sources]]
		Bucket         = "chromium-skia-gm"
		Dir            = "nano-json-v1"

		[Ingesters.nano.ExtraParams]
		TraceService   = "localhost:9090"


	### PDF ingester ############################################################
	[Ingesters.pdf]
	RunEvery       = "15m"                
	NCommits       = 100                  
	MinDays        = 21                   
	StatusDir      = "./ingest_status"    
	MetricName     = "pdf-raster"         

		[[Ingesters.pdf.Sources]]
		Bucket         = "chromium-skia-gm"
		Dir            = "dm-json-v1"

		[Ingesters.pdf.ExtraParams]
		InputImagesBucket  = "chromium-skia-gm"
		InputImagesDir     = "dm-images-v1"

		OutputJsonBucket   = "skia-infra-gm"
		OutputJsonDir      = "dm-json-v1"

		OutputImagesBucket  = "skia-infra-gm"
		OutputImagesDir     = "dm-images-v1"
		PdfCacheDir         = "/var/lib/pdfcachedir"
