---
- hosts: 127.0.0.1
  connection: local
  remote_user: chrome-bot
  become_user: root
  become: yes
  become_method: sudo
  vars:
    image: /opt/rpi_img/2016-03-18-raspbian-jessie-lite.img
    # 8192 * 512
    offset_boot: 4194304
    # 131072 * 512
    offset_root: 67108864
  tasks:
    - file: path=/opt/raspberrypi/root state=directory

    - mount: src="{{image}}" name="/opt/raspberrypi/root" fstype="auto" opts="loop,offset={{offset_root}},noauto" state="mounted"

    - command: cp /usr/bin/qemu-arm-static /opt/raspberrypi/root/usr/bin/
    # These do NOT use the mount: command, as it does not currently support --rbind.
    # Additionally, I don't necessarily want to update fstab
    - command: mount --rbind /dev   /opt/raspberrypi/root/dev
    - command: mount -t proc none   /opt/raspberrypi/root/proc
    - command: mount -o bind /sys   /opt/raspberrypi/root/sys

    # Comment out this line in this file so as to avoid
    # qemu: uncaught target signal 4 (Illegal instruction) - core dumped
    # Illegal instruction (core dumped)
    - lineinfile: dest=/opt/raspberrypi/root/etc/ld.so.preload line="/usr/lib/arm-linux-gnueabihf/libarmmem.so" state=absent
    - lineinfile: dest=/opt/raspberrypi/root/etc/ld.so.preload line="#/usr/lib/arm-linux-gnueabihf/libarmmem.so" state=present

    - name: Create the startup script
      copy: src=start_swarming dest=/opt/raspberrypi/root/opt/start_swarming owner=root group=root mode=0755

    - name: Create the swarming service
      copy: src=swarming dest=/opt/raspberrypi/root/etc/init.d/swarming owner=root group=root mode=0755

  handlers:

