GitRepoDir     = "/mnt/pd0/gold/skiarepo"              # Directory location for the Skia repo.
GitRepoURL     = "https://skia.googlesource.com/skia"  # URL location for the repo.

[Ingesters]
  ### Gold ingester ############################################################
  [Ingesters.gold]
  RunEvery       = "5m"
  NCommits       = 75
  MinDays        = 3
  StatusDir      = "/mnt/pd0/gold/ingest_status"
  MetricName     = "gold-ingest"
  LocalCache     = true

    [[Ingesters.gold.Sources]]
    Bucket         = "skia-infra-gm"
    Dir            = "dm-json-v1"

    [[Ingesters.gold.Sources]]
    Bucket         = "chromium-skia-gm"
    Dir            = "dm-json-v1"

    [[Ingesters.gold.Sources]]
    Bucket         = "skia-infra-gm"
    Dir            = "pdf/dm-json-v1"

    [Ingesters.gold.ExtraParams]
    TraceService   = "localhost:9090"


  ### Gold trybot ingester #####################################################
  [Ingesters.gold-trybot]
  RunEvery       = "5m"
  NCommits       = 10
  MinDays        = 7
  StatusDir      = "/mnt/pd0/gold/ingest_status"
  MetricName     = "gold-ingest-trybot"
  LocalCache     = true

    [[Ingesters.gold-trybot.Sources]]
    Bucket         = "skia-infra-gm"
    Dir            = "trybot/dm-json-v1"

    [[Ingesters.gold-trybot.Sources]]
    Bucket         = "chromium-skia-gm"
    Dir            = "trybot/dm-json-v1"

    [Ingesters.gold-trybot.ExtraParams]
    TraceService   = "localhost:9090"
    RietveldCodeReviewURL = "https://codereview.chromium.org"
    GerritCodeReviewURL = "https://skia-review.googlesource.com"
