[Common]

ResourcePath          = "/Users/humper/work/gocode/src/go.skia.org/infra/fuzzer"
FuzzOutputGSBucket	  = "skia-fuzzer"
DoOauth               = true
OauthCacheFile        = "/Users/humper/work/gocode/src/go.skia.org/infra/perf/google_storage_token.data"
OAuthClientSecretFile = "/Users/humper/work/gocode/src/go.skia.org/infra/perf/client_secret.json"
Local                 = false

[FrontEnd]

Port           = ":8000"  # "HTTP service address (e.g., ':8000')")
GraphiteServer = "skia-monitoring-b:2003" # address of the graphite server
RedirectURL    = "https://fuzzer.skia.org/oauth2callback/" # OAuth2 redirect URL
ForceLogin     = true

[Fuzzer]

CachePath     = "/Users/humper/work/fuzzer_cache"
SkiaSourceDir = "/Users/humper/work/skia"

[Generators]

	[Generators.dummy]
	Weight=0
	
	[Generators.paths]
	Weight=1
	
	[Generators.fail]
	Weight=0
