[Common]

TileDir        = "/mnt/pd0/data/tileStore3"             # Path where tiles will be placed.
GitRepoDir     = "/mnt/pd0/data/skia"                   # Directory location for the Skia repo.
GraphiteServer = "skia-monitoring:2003"                 # Where is Graphite metrics ingestion server running.
DoOauth        = false                                  # Run through the OAuth 2.0 flow on startup, otherwise use a GCE service account.
Local          = false                                  # Running locally if true. As opposed to in production.

[Ingesters]

	[Ingesters.nano]

	RunEvery       = "5m"                                   # How often the ingester should pull data from Google Storage.
	RunTrybotEvery = "1m"                                   # How often the ingester to pull trybot data from Google Storage.
	Commits        = 10                                    # Minimum number of commits that should be ingested.
	MinDays        = 1                                      # Minimum number of days that should be covered by the ingested commits.
	StatusDir      = "/mnt/pd0/data/ingest_status"               # Path where the ingest process keeps its status between restarts.
	MetricName     = "nano-ingest"                          # Graphite metric name to use for this ingester

	[Ingesters.nano.ExtraParams]

    GSBucket       = "chromium-skia-gm"
		GSDir          = "nano-json-v1"							# Google storage directory to draw from

[Ingesters.nano-trybot]

	RunEvery       = "5m"                                   # How often the ingester should pull data from Google Storage.
	RunTrybotEvery = "1m"                                   # How often the ingester to pull trybot data from Google Storage.
	Commits        = 10                                    # Minimum number of commits that should be ingested.
	MinDays        = 1                                      # Minimum number of days that should be covered by the ingested commits.
	StatusDir      = "/mnt/pd0/data/ingest_status"          # Path where the ingest process keeps its status between restarts.
	MetricName     = "nano-trybot"                          # Graphite metric name to use for this ingester

	[Ingesters.nano-trybot.ExtraParams]

    GSBucket       = "chromium-skia-gm"
		GSDir          = "trybot/nano-json-v1"					# Google storage directory to draw from
