GitRepoDir     = "/mnt/pd0/skiaperf/repo"                         # Directory location for the Skia repo.
GitRepoURL     = "https://skia.googlesource.com/git-master-skia"  # URL location for the repo.

[Ingesters]

	### Nano bench ingester ############################################################
	[Ingesters.nano]
	RunEvery       = "5m"
	NCommits       = 10
	MinDays        = 2
	StatusDir      = "/mnt/pd0/skiaperf/ingest_status"
	MetricName     = "android-master-skia-ingest"

		[[Ingesters.nano.Sources]]
		Bucket         = "skia-perf"
		Dir            = "android-ingest"
