GitRepoDir     = "/mnt/pd0/skiaperf/repo"              # Directory location for the Skia repo.
GitRepoURL     = "https://skia.googlesource.com/skia"  # URL location for the repo.

[Ingesters]

	### Nano bench ingester ############################################################
	[Ingesters.nano]
	RunEvery       = "1m"
	NCommits       = 10
	MinDays        = 2
	StatusDir      = "/mnt/pd0/skiaperf/ingest_status"
	MetricName     = "nano-ingest"

		[[Ingesters.nano.Sources]]
		Bucket         = "skia-perf"
		Dir            = "ct/10k"

		[[Ingesters.nano.Sources]]
		Bucket         = "skia-perf"
		Dir            = "nano-json-v1"

	### Nanobench Trybot ingester ############################################################
	[Ingesters.nano-trybot]
	RunEvery       = "1m"
	NCommits       = 10
	MinDays        = 2
	StatusDir      = "/mnt/pd0/skiaperf/trybot_ingest_status"
	MetricName     = "nano-trybot-ingest"

    [[Ingesters.nano-trybot.Sources]]
    Bucket         = "skia-perf"
    Dir            = "trybot/nano-json-v1"

